### ISSUE TITLE
[P0 Bug] How to draw Icon layer didn't have react

### ISSUE THREAD

**Issue by sos418** [uber/kepler.gl#113]
<img width="286" alt="2018-06-10 8 23 22" src="https://user-images.githubusercontent.com/13904119/41197200-da12ee46-6c87-11e8-8998-c3fc1b5cd9fe.png">

**Comment by Magamonsta** [comment]
also this is the error that is thrown when you try to select the information icon 
![kepler_icon_error](https://user-images.githubusercontent.com/38330505/41308714-b73dfaae-6e4a-11e8-99e2-ec2cd752176f.PNG)

**Comment by Magamonsta** [comment]
for those interested, here is a workaround for customizing icons
in your csv add a column named icon
scroll through the following url [https://raw.githubusercontent.com/uber/kepler.gl/master/src/layers/icon-layer/svg-icons.json](url) and find which icon you want to use, there are about 150, some of the options are brake, dangerous, swerve, android, apple, etc.
then for each entry in your csv add the icon id you wish to use
then when you upload the csv, kepler should automatically recognize the icon column

**Comment by chrisirhc** [comment]
To clarify the steps to reproduce the issue are: click on "How To Draw Icon Layer"?

**Comment by Magamonsta** [comment]
yes, when you select the information icon right before "How To Draw Icon Layer"

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/131
