### ISSUE TITLE
Add "Share" wording on Save/Export button

### ISSUE THREAD

**Issue by chrisirhc** [uber/kepler.gl#122]
Currently:
![image](https://user-images.githubusercontent.com/132584/41579692-d0b647c8-734c-11e8-87c5-ab89f3005975.png)

Proposed:
![image](https://user-images.githubusercontent.com/132584/41579746-08b49e4a-734d-11e8-8cfc-d917831a92c6.png)

**Comment by matheusmonte** [comment]
Hey @chrisirhc , 

Can I get this issue?

**Comment by chrisirhc** [comment]
@matheusmonte go for it! We're happy to accept contributions.

**Comment by matheusmonte** [comment]
@chrisirhc I open a PR to solve this issue :)
