### ISSUE TITLE
Possible Bug: Integer column appears as boolean

### ISSUE THREAD

**Issue by pblack-trulia** [uber/kepler.gl#124]
I've loaded some centroids that have valid coordinates in both geojson and csv (just to see if there was a difference). Map renders, but if I want to classify the data based upon an integer column Kepler recognizes the data, but incorrectly casts the data as a Boolean. Anyone else having the same issue?

**Comment by heshan0131** [comment]
Currently if a column only contain 1 or 0, it will be created as boolean, a workaround is to put in 1.0

**Comment by pblack-trulia** [comment]
Hi Shan, the file actually contains integers from 1-5. Sorry my screencap wasn't clearer...

**Comment by yiyaya66** [comment]
thank you @pblack-trulia. We will make changes to the logic so that 1 & 0 will not be detected as boolean.

**Comment by erickndava** [comment]
> Hi Shan, the file actually contains integers from 1-5. Sorry my screencap wasn't clearer...

I am also having same issue. I have a field with 1s and 2s.
