### ISSUE TITLE
luma.gl - multiple VERSIONs detected: 4.0.6 vs 5.3.0

### ISSUE THREAD

**Issue by ChunhongZhao** [uber/kepler.gl#129]
I am using both deck.gl and kepler.gl in same project, I met this issue `luma.gl - multiple VERSIONs detected: 4.0.6 vs 5.3.0`, can anyone help with this issue?

**Comment by ibgreen** [comment]
My understanding is that kepler.gl is currently using an older version of deck.gl. You'll have to match the version of deck.gl and luma.gl you are installing to the older versions that kepler.gl is using. You can check what versions kepler.gl in the console.log, or by using `npm ls` in your repo, or check the package.json in kepler.gl etc.

That said, I do believe an upgrade of kepler.gl to the latest deck.gl is in the works @heshan0131

**Comment by heshan0131** [comment]
That is correct. I’m working on upgrading kepelr.gl to deck.gl v5, where luma is no longer a peer dependency. At the mean time, you need to downgrade luma to match the version Kepler.gl required.

**Comment by ChunhongZhao** [comment]
Thank you so much @ibgreen @heshan0131 
It works now when I downgraded luma to 4.0.6.

**Comment by locomotif** [comment]
just incase anyone else stumbles onto this thread.  Using `yarn upgrade-interactive --latest`, and upgrading from  `"deck.gl": "^4.1.0"` to `"deck.gl": "^5.3.2"`, did not correctly update the`yarn.lock` file.  It correctly included `luma.gl@^5.3.0`, but did not remove `luma.gl@^4.0.3`.  I had to remove deck.gl with `yarn remove deck.gl` and then just add it back again.

**Comment by ChunhongZhao** [comment]
Just a quick question regarding deck.gl version, what’s plan for upgrading deck.gl to 5.3?


Best Regards,


Chunhong(Ella) Zhao / Full Stack Engineerchunhong.zhao@grabtaxi.com / +8613572006254
Grab Technology (Beijing) Co., LtdRoom 212, Building A, Raycom Infotech Park, 2 Kexueyuan South Road, Haidian District, Beijing Chinahttp://www.grab.com


On Jul 14, 2018, 13:39 +0800, Bernardo Leigh <notifications@github.com>, wrote:
> just incase anyone else stumbles onto this thread. Using yarn upgrade-interactive --latest, and upgrading from "deck.gl": "^4.1.0" to "deck.gl": "^5.3.2", did not correctly update theyarn.lock file. It correctly included luma.gl@^5.3.0, but did not remove luma.gl@^4.0.3. I had to remove deck.gl with yarn remove deck.gl and then just add it back again.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
_Grab is hiring. Learn more at *https://grab.careers 
<https://grab.careers/>*_


By communicating with Grab Inc and/or its 
subsidiaries, associate companies and jointly controlled entities (“Grab 
Group”), you are deemed to have consented to processing of your personal 
data as set out in the Privacy Notice which can be viewed at 
https://grab.com/privacy/ <https://grab.com/privacy/>


This email contains 
confidential information and is only for the intended recipient(s). If you 
are not the intended recipient(s), please do not disseminate, distribute or 
copy this email and notify Grab Group immediately if you have received this 
by mistake and delete this email from your system. Email transmission 
cannot be guaranteed to be secure or error-free as any information therein 
could be intercepted, corrupted, lost, destroyed, delayed or incomplete, or 
contain viruses. Grab Group do not accept liability for any errors or 
omissions in the contents of this email arises as a result of email 
transmission. All intellectual property rights in this email and 
attachments therein shall remain vested in Grab Group, unless otherwise 
provided by law.

**Comment by ChunhongZhao** [comment]
@heshan0131  I've subscribed your PR, thanks for your quick update.
