### ISSUE TITLE
Export Config no longer includes dataset(s)

### ISSUE THREAD

**Issue by mgorlick** [uber/kepler.gl#133]
Until very recently the "Export Config"  option under the Save/Export button automatically included the data set (as json) bundled up with the configuration settings. Has that behavior been changed? I confess that I found the bundling appealing. It reduced sharing visualizations to a triviality. What is the recommended practice for sharing now?

**Comment by yiyaya66** [comment]
@mgorlick could you share steps (incl. screenshots if possible) to reproduce this issue?

**Comment by mgorlick** [comment]
The issue is bogus and was merely a user error on my part. Please accept my apology.
