### ISSUE TITLE
GeoJSON won't upload

### ISSUE THREAD

**Issue by PauloDeMello** [uber/kepler.gl#174]
**Describe the bug**
Hi, I've uploaded a GeoJSON to the webapp, but it still says it is uploading (around 30 minutes).

[major-roads-link-network2016.zip](https://github.com/uber/kepler.gl/files/2218558/major-roads-link-network2016.zip) [GeoJSON]

**Screenshots**
![keplergl](https://user-images.githubusercontent.com/41569576/43066676-3480dc52-8e5d-11e8-8b7a-e667fac1487b.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Additional context**
(GeoJSON was converted from a ShapeFile in mapshaper)
[major-roads-link-network2016.zip](https://github.com/uber/kepler.gl/files/2218563/major-roads-link-network2016.zip) [ShapeFile]

**Comment by matheusmonte** [comment]
@PauloDeMello Can you provide a screenshot from your browser console ?
