### ISSUE TITLE
Time range slider play automatically when data was loaded

### ISSUE THREAD

**Issue by ChunhongZhao** [uber/kepler.gl#175]
I am going to play time series data automatically, currently, the TimeRangeSlider could not play automatically, any suggestion for this issue?

**Comment by ChunhongZhao** [comment]
I found a solution for this issue, just using `setFilter` method to update time range, it works for me, please close this issue and thanks

**Comment by vararp25** [comment]
Hi @ChunhongZhao am trying to add TimeSlider to reduce the number of data points on screen. The setFilter method is not working for me can you share your code snippet?
