### ISSUE TITLE
question: wehre to modify the legend

### ISSUE THREAD

**Issue by geoHeil** [uber/kepler.gl#179]
Where can I modify the legend which is generated when exporting an image?

I could not find it here: https://github.com/uber/kepler.gl/blob/master/src/components/common/color-legend.js#L152

![kepler-gl](https://user-images.githubusercontent.com/1694964/43270376-3404af5c-90f5-11e8-9486-b0a23188c325.png)

I.e. changing the color of Kepler.gl logo or adding some custom text

**Comment by heshan0131** [comment]
it's inside the map-control component https://github.com/uber/kepler.gl/blob/master/src/components/map/map-control.js#L317-L320

**Comment by geoHeil** [comment]
thanks
