### ISSUE TITLE
When a json with conf+data is loaded, the background selector disappears

### ISSUE THREAD

**Issue by Lenninlasd** [uber/kepler.gl#185]
**Describe the bug**
When a json with conf+data is loaded, the background selector disappears and it doesn't preserve the json background.

**To Reproduce**
1. Go to http://kepler.gl/#/demo/earthquakes
2. Click on Export => export Config
3. Check on Export Current Map and save the json file.
4. Go to http://kepler.gl/#/demo
5. Load the json on "Add Data" button.
6. You can't see the basemaps list.

**Expected behavior**
We expect keplergl read the default basemap provided by the json file, and keplergl put it on the background.
We expect the list of all backgrounds is not removed (As we can see when we load directly .
http://kepler.gl/#/demo/earthquakes)

**Screenshots**

Original basemaps with: http://kepler.gl/#/demo/earthquakes
![image](https://user-images.githubusercontent.com/7197750/43596933-3f34bc2c-9646-11e8-8300-00d26409e33e.png)

When earthquakes json is loaded
![image](https://user-images.githubusercontent.com/7197750/43596812-f2a007b8-9645-11e8-9445-4b43be043207.png)

**Laptop :** MacBook (Retina, 12-inch, Early 2016)
 - OS: macOs High Sierra v10.13.5
 - Browser: chrome
 - Version 67.0.3396.99

**Additional context**
I would be happy to PR :)

**Comment by heshan0131** [comment]
I have a fix for this out, will deploy it later today!

**Comment by Lenninlasd** [comment]
@heshan0131 Great! thanks for your quick response.

**Comment by heshan0131** [comment]
@Lenninlasd this should be fixed with the new deployment, can you confirm and resolve this issue?

**Comment by Lenninlasd** [comment]
Yes, it's fixed on the demo page and in my local environment. Thank for you hard work!
