### ISSUE TITLE
example demo-app error

### ISSUE THREAD

**Issue by muka** [uber/kepler.gl#192]
**Describe the bug**
After cloning the repo and following the instructions in README of `https://github.com/uber/kepler.gl/tree/master/examples/demo-app`
there is a token error on `Provider`

**To Reproduce**
1. git clone https://github.com/uber/kepler.gl/
2. cd examples/demo-app
3. npm i
4. npm start

**Expected behavior**
```
ERROR in ./src/main.js
Module build failed: SyntaxError: Unexpected token (36:2)

  34 | 
  35 | const Root = () => (
> 36 |   <Provider store={store}>
     |   ^
  37 |     <Router history={history}>
  38 |       <Route path="/(:id)" component={App} />
  39 |       <Route path="/demo/(:id)" component={App} />
```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Comment by heshan0131** [comment]
Looks like babel-preset react-is not added.

**Comment by heshan0131** [comment]
Can you try change `"kepler.gl": "../.."` in package.json to `"kepler.gl": "^0.0.28"` then run 
`rm -r node_modules && yarn --ignore-engines`
after install `npm start`

**Comment by muka** [comment]
Yep, I used a fresh clone but is working now! Thanks

**Comment by jodevsa** [comment]
Same problem
