### ISSUE TITLE
Debugging keepler.gl

### ISSUE THREAD

**Issue by behuda** [uber/kepler.gl#203]
I cloned the repo, and ran npm start, which started the demo app from examples folder.
I wanted to debug the keepler code by putting breakpoint in source code, the demo app code was bundled, so was not able to do that.
I tried changing the all the imports of "kepler.gl" in the demo app code to ".../../..src" like that 
but was not to compile the code, 
I got webpack error "You may need an appropriate loader to handle "
then i modified the webpack.config.ts  to include the ../../src dir
```
 include: [
          join(__dirname, 'src'),
          join(__dirname, '../src')

but still was not to compile the code
module not found error was coming

**Comment by macrigiuseppe** [comment]
Hi @behuda,
The example app code is compiled by it also comes with sourcemaps so you can easily debug any aspect of Kepler.gl. 
Make sure when you open the app in browser the console is open as well and you will have access to source maps. 
If you are using Chrome on a Mac. Once the debug console is open, go to source and search for the file you want to debug using: shift+command+o, remove "@" before typing the name of the file
