### ISSUE TITLE
Failed to Invert Matrix Error when uploading GeoJson file specifically

### ISSUE THREAD

**Issue by omegadeep10** [uber/kepler.gl#205]
**Describe the bug**
Uploading a valid geojson file to Kepler.gl's demo site causes the upload screen to hang. The browser console shows the error "Failed to invert matrix". 
![image](https://user-images.githubusercontent.com/14183626/44428641-faecc880-a562-11e8-8882-2adfa9fc536b.png)

This error occurs when using Firefox Developer Edition 62.0b19 (64-bit) and Chrome Version 68.0.3440.106 (Official Build) (64-bit)

I can use the demo application just fine when I upload my CSV data. All the analysis and features seem to work. I simply can't upload geojson files. 

Here is the specific geojson file I was using:
[voting_precinct (3).zip](https://github.com/uber/kepler.gl/files/2308022/voting_precinct.3.zip)

**To Reproduce**
1. In either browser specified above, navigate to http://kepler.gl/#/demo
2. Drop the .json file attached above.
3. Press F12 to view the "Failed to invert matrix" error in the console.

**Expected behavior**
The geojson file to be parsed and displayed on the map as a new layer.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser See Above
 - Version Kepler 1.0

**Additional context**

**Comment by heshan0131** [comment]
@omegadeep10 The coordinates in your geojson is not in latitude and longitude space. Looks like it's in XY space, that's why kepler.gl is running into error. `[2470692.72894991,1050870.95316139],[2470097.22981283,1050176.83668545]`

Where did you obtain this file? QGIS should have functions to convert XY coordinates into lat lng.

**Comment by omegadeep10** [comment]
I obtained the data from a public dataset of shapefiles, and converted it to geojson using mapshaper.org. I guess something went wrong in the process, I'll figure it out. 

Closing this since it is user error.

Thanks!
