### ISSUE TITLE
Can i trace the current zoom lat lon/ the map not refresh the zoom after addDataToMap

### ISSUE THREAD

**Issue by rmanisthebest** [uber/kepler.gl#209]
I know it has no dynamic way to update the mapdata yet, so i use the suggestion with addDataToMap each time, but it just config it using the zoom in config. Is there any ways to solve it?

i saw similar issue of it. i tried to use getMapConfig() to get current config b4 addDatatoMap. but it seems not what i am seeking for that still back to origin config setting. Thanks

**Comment by heshan0131** [comment]
@rmanisthebest you can `getMapConfig()` will get you the current config of the entire kepler.gl state. you only need to 

```
cosnt mapConfig = KeplerGLSchema.getConfigToSave()
const currentMapState= mapConfig.config.mapState

// replace saved mapState with current mapState
const modifySavedConfig = {
  version: savedConfig.version,
  config: {
    ...savedConfig.config,
    mapState: currentMapState
  }
};

// call addDataToMap
this.props.dispatch(
      addDataToMap({
        datasets: [...],
        options: {
          centerMap: false
        },
        config: modifySavedConfig
      })
    );

```

Let me know if this works

**Comment by rmanisthebest** [comment]
Works, thanks!!
