### ISSUE TITLE
Image export seems broken

### ISSUE THREAD

**Issue by schnerd** [uber/kepler.gl#212]
**Describe the bug**
When using **Share** -> **Export Image**, the image never finishes loading. The following errors appear in the developer console:

Chrome
![image](https://user-images.githubusercontent.com/875591/44547652-3669cd00-a6f2-11e8-8a1b-c820bf251131.png)

Safari
![image](https://user-images.githubusercontent.com/875591/44547722-5ef1c700-a6f2-11e8-9074-89cfc4e2e621.png)

**To Reproduce**
1. Go to http://kepler.gl/#/demo
2. Click on 'Share'
3. Click on 'Export Image'

**Comment by schnerd** [comment]
Hmmm actually I just found #150. Disabling cache in chrome fixed the issue.

Is there anyway we can force a cache invalidation for that resource in cloudfront?

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/360
