### ISSUE TITLE
Uncaught TypeError: Cannot read property 'label' of undefined at Layer.getVisualChannelDescription (base-layer.js:312)

### ISSUE THREAD

**Issue by guidorice** [uber/kepler.gl#213]
**Describe the bug**

Uncaught TypeError: Cannot read property 'label' of undefined
at Layer.getVisualChannelDescription (base-layer.js:312)
at map-legend.js:116
at Array.map ()
at MapLegend (map-legend.js:115)
at StatelessComponent.render (ReactCompositeComponent.js:42)
at ReactCompositeComponent.js:793
at measureLifeCyclePerf (ReactCompositeComponent.js:73)
at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)

**To Reproduce**

1. Go to http://kepler.gl/#/demo/earthquakes
2. Show JS Console
3. Click on Show Legend
4. Click on Add Layer
5. See JS exception

**Expected behavior**

No JS Exception

**Desktop**
 - OS: OS X
 - Browser: chrome
 - Version 68

**Additional context**

The root cause seems to after Add Layer and  before a layer type is selected, the legend has missing information (label). The problem is in map-legend.js MapLegend function. You can filter the layers to remove the not-yet-typed layer. Would you like me to submit a PR for this?

```js
import Layer from '../../layers/base-layer';
...
{layers.filter(layer => layer.constructor !== Layer).map((layer, index) => {
      ...
```

**Comment by BBeran** [comment]
Does this have any user side effects? Performance etc. or is it just seeing an empty legend if you haven't set up a layer yet?

**Comment by koranins** [comment]
Yes it does.  Legend will not show up if you reorder a layer with no type to the top.
![image](https://user-images.githubusercontent.com/30090379/44550278-f4845b00-a6e0-11e8-86ae-cf7af19c09b4.png)
