### ISSUE TITLE
Map related events in kepler.gl

### ISSUE THREAD

**Issue by devcer** [uber/kepler.gl#216]
Hi,
I started exploring kepler.gl but found no luck in understanding from the past 2 days. I was looking for documentation on regular map related events like drawing a marker, getting latlng using on click event handlers, image overlays etc. in kepler.gl but I couldn't find any until now. Can someone guide me through where I can find the related info. I finally want to click points and draw a polygon on the map.

**Comment by heshan0131** [comment]
All these map events is handled by `react-map-gl` and `deck.gl`. in map-container, kepler.gl sends [event handler](https://github.com/uber/kepler.gl/blob/master/src/components/map-container.js#L347-L348) to deck.gl. the `onLayerHover` and `onLayerClick` events are all redux actions. 

We are planning to add click and draw polygon function to kepler.gl using [nebula.gl](https://neb.gl/#/).  
That being said, it probably will take another month or 2 until it is launched.

If you want to play with your own implementation, You can use `reducer.plugins` (documented in the readme, and exmaples/custom-reducer) to add your own action handler, override the default [`LAYER_CLICK`](https://github.com/uber/kepler.gl/blob/master/src/reducers/vis-state.js#L67), [`MAP_CLICK`](https://github.com/uber/kepler.gl/blob/master/src/reducers/vis-state.js#L83) action

**Comment by devcer** [comment]
Hey @heshan0131, we are trying this out. you can go ahead and close this issue. Thanks again.

**Comment by RameshPaul** [comment]
Hey @heshan0131 
I would like to know when your planning to release click and draw polygon functions to kepler.gl using [nebula.gl ](https://github.com/uber/nebula.gl), I am also trying to use [nebula.gl ](https://github.com/uber/nebula.gl) to draw polygons on the kepler.gl.
