### ISSUE TITLE
Could Sidebar not affected by addDataToMap()

### ISSUE THREAD

**Issue by rmanisthebest** [uber/kepler.gl#232]
In my app, i did some dynamic update every sec and using the method from here: http://vis.academy/#/kepler.gl/3-load-config
but the sidebar and tooltip will keep re-rendering because of the "new" config dispatch to addDataToMap(). Is there any method to avoid it.

One more question: is there ways to get current dataset of layers?

**Comment by heshan0131** [comment]
@rmanisthebest Can you describe the exact function you called, and what is the intended behavior?

**Comment by rmanisthebest** [comment]
Oh, thanks for the reply. Actually, it is solved and i will close it now.

I was using addDataToMap() to dispatch the whole config of visState. Because of updating whole config, react refresh all the component including the sidebar and tooltip. So, it used property spread notation and overwrite the action to prevent react updating the whole kepler map component.

**Comment by Deviljunction** [comment]
Hi @rmanisthebest 
Will you mind sharing on what exactly did you do to get it work? It would be a great help.
