### ISSUE TITLE
Text label in Point layer only supports ascii.

### ISSUE THREAD

**Issue by wonderino** [uber/kepler.gl#238]
By default, only characters in the Ascii code range 32-128 are included in Deck.gl's TextLayer. Can I use TextLayer's characterSet prop in Kepler.gl?

**Comment by heshan0131** [comment]
Unfortunately no at the moment. What language are you using?

**Comment by heshan0131** [comment]
@javidhsueh is this something we can add to the text layer support in kepler.gl? We could do a scan on all the strings and get a characterSet domain to set on the textLayer.

**Comment by wonderino** [comment]
I'm using CJK. Thanks.

**Comment by heshan0131** [comment]
Closing it for now, please test it and let us know if there is anything else
