### ISSUE TITLE
Dynamically loading kepler json from the web

### ISSUE THREAD

**Issue by brandontlocke** [uber/kepler.gl#256]
I'm wondering if it's possible to develop a method for importing a Kepler json file that's hosted externally via a URL.

For context: I'm teaching students to use this in a class, and we don't have the ability to spin up our own Kepler instance. I'd like the students to be able to provide access to all of the interactive features of the maps. I know they can make the exported json file available to download and allow others to import it themselves, but I think it would be awesome if they could post the json file somewhere (perhaps as a Github gist?) and then provide readers a URL like http://kepler.gl/?data=gist.github.com/etc.

I think this would be a great way for people to make their maps shareable without access to a server without requiring you to store anything.

**Comment by chrisirhc** [comment]
@macrigiuseppe this is related to recent discussions

**Comment by macrigiuseppe** [comment]
@brandontlocke I just created a new pull request to be able to load files using URLS.
https://github.com/uber/kepler.gl/pull/260
