### ISSUE TITLE
As user I should be able to share my map with other users by providing a simple link

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#262]
**Is your feature request related to a problem? Please describe.**
Users should be able to generate maps and share them with other users with URLs.

**Describe the solution you'd like**
The following options are being considered:
- http://kepler.gl/#/demo?map/[Data/Kepler.gl_URL]
- http://kepler.gl/#/demo?mapUrl=[Data/Kepler.gl_URL]

**Describe alternatives you've considered**

**Additional context**
The user is required to store their kepler.gl in a reachable location using a URL.
It is required the kepler.gl file location will accept CORS from kepler.gl website (or current kepler.gl domain).

***Contraints***
- Passing a full url to react router can be challenging because it may be difficult to match the actual URL and not user friendly.

I am more thinking about something like: __kepler.gl/#/map/mapId__.
In order to generate the mapId we can use a URL shorten service to generate and map the URL to unique and short identifier.
I am considering TinyURL as shorten service since they provide an npm package. Once users save their map to their favorite cloud storage, we can grab the URL and convert to a unique identifier using the TinyURL library. 

This is an example:
- Original: https://raw.githubusercontent.com/uber-web/kepler.gl-data/remote-file-test/earthquakes/keplergl.json
- Short: https://tinyurl.com/yd8o22ph
Once the short version is generated we can provide users with the new Kepler.gl link: __http://kepler.gl/#/map/yd8o22ph__

Users can generate their own short URLs and pass them to Kepler.

Are we constrained ourselves to TinyUrl service?
In order to provide a more flexible service, I am thinking about the ability to use multiple url shorten services. We could specify a parameter in the url to use a particular url shorten service. The previous URL can also be written as: __http://kepler.gl/#/map/yd8o22ph/bitly__

** Questions **
How are we going to integrate this as part of Kepler.gl core?

**Comment by macrigiuseppe** [comment]
@bumbeishvili Thank you for the message.

The current task defines two features:
- generate and store maps (IN PROGRESS)
- share the generated link with other users (CURRENTLY AVAILABLE)

Once the first feature will be completed, I will be closing this issue.

**Comment by macrigiuseppe** [comment]
This is currently implemented using the following approach:
- http://kepler.gl/#/demo?mapUrl=[Data/Kepler.gl_URL]

The short url approach is not considered for this time yet

**Comment by jakeswim145** [comment]
@bumbeishvili  @macrigiuseppe  How do I go about creating an external link for my map, I have tried to follow your instructions from your post here
https://beta.observablehq.com/@bumbeishvili/kepler-gl-iframe

But when I follow my map data doesn't seem to load into kepler when the link opens. 

Here is my raw map file exported from kepler for reference

https://gist.githubusercontent.com/jakeswim145/d47bd98baf87a0d30431848881ec1101/raw/bc4a0bf7213326a508581376ea6b713f994ca167/chinaexports.json

If you could help me/ direct me on how is best to make this into a shareable and easly accessible map that would be fantastic.
Thanks in advanced!

**Comment by erickndava** [comment]
Hi @jakeswim145 . I was able to successfully load your visualisation as per the tutorial here - https://beta.observablehq.com/@bumbeishvili/kepler-gl-iframe

Below is the link to your map
https://kepler.gl/#/demo?mapUrl=https://gist.githubusercontent.com/jakeswim145/d47bd98baf87a0d30431848881ec1101/raw/bc4a0bf7213326a508581376ea6b713f994ca167/chinaexports.json

I think the important thing is to add(append) your raw map file link to https://kepler.gl/#/demo?mapUrl=

That should work or something might be misbehaving on your side.

**Comment by jakeswim145** [comment]
@erickndava thanks for your assistance!
I'll make sure to do this step with my next map! 
Thanks

**Comment by macrigiuseppe** [comment]
@jakeswim145 @erickndava We are about to launch a new feature that will allow users to create and save maps directly into dropbox user account and automatically generate a permalink to share with other users. Stay tuned!!

**Comment by macrigiuseppe** [comment]
This has been implemented!

**Comment by pavan-elisetty** [comment]
@macrigiuseppe Hi , can you provide some navigation for the above i.e, saving to dropbox and sharing link , can it be done using py APIs or is it possible only through manually plotting in kepler.gl/demo webpage
