### ISSUE TITLE
Ability to upload maps to dropbox

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#263]
**Is your feature request related to a problem? Please describe.**
Users will be able to export the Kepler.gl file onto their Dropbox user account.

**Describe the solution you'd like**
When users export their configuration and data, they will have the ability to choose Dropbox as destination. Users must authenticate against Dropbox before they could perform the saving action.

***Auth Flow***
It is important to remember that Kepler.gl doesn't require a back end server to run on therefore all 
- User click on export map in the current Tab (aka parent tab)
- User will click on auth button which will redirect the user to dropbox by opening a new tab/window (aka child tab)
- The parent tab will subscribe to local storage events (required for other steps)
- After a successful login, dropbox will redirect the user to kepler.gl/#/auth which will read the auth token provided by dropbox and store in the local storage always remaining the child tab.
- The child tab will automatically close after storing the token.
-  The parent tab will receive the storage event and will read the auth token from local storage which will be used to upload and store the file in Dropbox. 

The above flow will allow users to work on their map and perform the Dropbox auth without losing their current work. If we were to log users on the same tab where they are performing their mapping they would lose their work completely because the app would reload completely after the auth process

****Constraints****
It looks like OAuth 2 protocol does not accept callback URIs with fragments, e.g. /#/demo. This could be an issue for our demo instance since we are running on github pages and the hash sign is required.
I will look for a possible solution.

**Describe alternatives you've considered**
- Google Drive: not available everywhere
- Box: their APIs are not as easy as Dropbox ones

**Additional context**
New UI is required

**Comment by macrigiuseppe** [comment]
Slight change to the implementation, In order to pass a token from child tab to the parent one we are now using the message feature and then storing the auth token into local storage

**Comment by chrisirhc** [comment]
Update based on today's discussion with @macrigiuseppe :
This feature is not yet released pending our work in #307 .

**Comment by macrigiuseppe** [comment]
Some legal requirements before we can release as well
In order to interact with Dropbox we have the following requirements:
- Create a [Dropbox Account](https://www.dropbox.com) for Kepler.gl
  - Dropbox basic account [terms of service](https://www.dropbox.com/terms)
  - Dropbox Business account [agreement](https://www.dropbox.com/business_agreement) and [terms of service](https://www.dropbox.com/terms)
- Once the account is created, we need to create a Dropbox App which will be used to interact with Dropbox API
  - Dropbox developer [terms and conditions](https://www.dropbox.com/developers/reference/tos)

Kepler.gl uses Dropbox javascript client and the code can be found [here](https://github.com/dropbox/dropbox-sdk-js).
