### ISSUE TITLE
Please make Uber styles public in mapbox

### ISSUE THREAD

**Issue by dsirov** [uber/kepler.gl#286]
Please make the four built-in (very nice!) kerpler.gl styles (Uber-Light, Uber-Dark, etc.) public in mapbox.
This way users can base their styles on these great ones.

Using the style.json referenced in the code does not work and rendering fails (it seems mainly because of missing fonts and such).

**Comment by heshan0131** [comment]
@dsirov 
Can you describe in what scenarios does rendering fails? How are you currently using kepler.gl?
