### ISSUE TITLE
Demo App Compilation Fails After Latest Commit

### ISSUE THREAD

**Issue by chaitnaya1391** [uber/kepler.gl#287]
Bug: The demo-app fails to compile.  

To reproduce, you could use the following Dockerfile.

`FROM alpine

EXPOSE 8080

RUN apk add --update nodejs nodejs-npm &&\
npm init -y &&\
npm install --save react react-dom &&\
apk add git &&\
cd home/ &&\
git clone https://github.com/uber/kepler.gl.git

ENV MapboxAccessToken=XXXXXXXX
ADD package.json /home/kepler.gl/examples/demo-app/

RUN cd /home/kepler.gl/examples/demo-app/ &&\
npm install &&\
npm start`

There are two changes in package.json: 
1. Removing --open in start scripts
2. Defining the host as --host 0.0.0.0 instead of localhost

Screenshot of compilation failure is as below. 
![kepler](https://user-images.githubusercontent.com/7519471/48794179-31331300-ed1f-11e8-8511-6fd1411fdcb0.PNG)

Tried this on both alpine and windows and facing the current challenge. 

PS: Tried this yesterday and was successful at building an image yesterday but after the latest commit, unable to do so. 

Thank you.

**Comment by heshan0131** [comment]
Closing it now, please re-open if still errors
