### ISSUE TITLE
AddDataButtonFactory export not working

### ISSUE THREAD

**Issue by aakim26** [uber/kepler.gl#291]
First of all, thank you for adding the additional exports from the side panel! I'm having trouble with the AddDataButtonFactory specifically- it seems to be undefined and therefore the injection isn't working. When I print out the exports, I see the following: 

<img width="483" alt="screenshot 2018-11-20 00 38 15" src="https://user-images.githubusercontent.com/13665982/48804041-6e1feb00-ecc8-11e8-9335-63a6c378480f.png">

**Comment by heshan0131** [comment]
Fixed in`v0.2.1-beta.0`
