### ISSUE TITLE
UI should reflect file load errors

### ISSUE THREAD

**Issue by chrisdiana** [uber/kepler.gl#294]
**Describe the bug**
The file upload spinner will keep spinning and not display any feedback on data processing error.

**To Reproduce**

1. Go to 'Get Started' > 'Load your Data' tab
2. Upload an empty JSON file or invalid JSON file - [empty.json.zip](https://github.com/uber/kepler.gl/files/2609338/empty.json.zip)

**Expected behavior**
The file uploader UI should display errors returned by the file handler and data processor. 

Just as the file uploader displays invalid file type errors ("File test.pdf is not supported."), this message should also display errors in the generated by processing.

1. User uploads valid file type but invalid file (such incorrect data format).
2. File handler and data processing runs
3. On processing error return message to UI and stop spinner

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 70.0.3538.102

**Additional context**
This bug is related to #281 and #253 but handling error messages seems to be the underlying issue.

**Comment by heshan0131** [comment]
We are currently working on this. You can follow the rfc here
https://github.com/uber/kepler.gl/issues/307

**Comment by chrisdiana** [comment]
Closing because duplicate.
