### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Legolash2o** [uber/kepler.gl#297]
Hello, 

I'm Struggling to find a proper guide to install on Linux Kepler.gl, can anyone assist?

For example it says "Install
Install node (> 6), yarn, and project dependencies". What are the "dependencies"?

**Comment by LHdT** [comment]
> Hello,
> 
> I'm Struggling to find a proper guide to install on Linux Kepler.gl, can anyone assist?
> 
> For example it says "Install
> Install node (> 6), yarn, and project dependencies". What are the "dependencies"?

It means that once you got Node instaled, you should use Node Package Manager to install dependencies.
So run this on project root folder
`$ npm install`

all dependencies you need as well as scripts you will use to run demo app are listed on package.json

**Comment by LHdT** [comment]
inspect your code for  const MAPBOX_TOKEN = process.env.MapboxAccessToken;
and then change it by
const MAPBOX_TOKEN = 'pk.eyJ1Ijo**nY29ycG9yYXRpdm9qYS***aXczZ3hlc2YwMDBrMm9wYnRqd3gyM****AGb6AA';
regards

**Comment by heshan0131** [comment]
@LHdT thanks for helping out. We haven't tried installing kepler.gl in a Linux system. Do you want to write up a simple doc about that? You can posted it in this issue and we sill add it to our README

**Comment by macrigiuseppe** [comment]
> inspect your code for const MAPBOX_TOKEN = process.env.MapboxAccessToken;
> and then change it by
> const MAPBOX_TOKEN = 'pk.eyJ1Ijo**nY29ycG9yYXRpdm9qYS**_aXczZ3hlc2YwMDBrMm9wYnRqd3gyM_***AGb6AA';
> you'd need to get an access token.
> regards

@Legolash2o @LHdT you don't to update the code, you can simply export your mapbox token in your terminal shell like this:
```bash
$ export MapboxAccessToken=[MapboxAccessToken]
```

**Comment by heshan0131** [comment]
closing for now. please reopen if you have further questions
