### ISSUE TITLE
My geojson file is not loading.

### ISSUE THREAD

**Issue by spazznolo** [uber/kepler.gl#324]
The file loads on mapshaper, with shapes and information intact, however when I attempt to add it to kepler, it is perpetually 'uploading'. I made the file very small to make sure it wasn't just a long load time. I've attached a link to the geojson file in question.

[https://github.com/spazznolo/kepler.test](url)

**Comment by chintanp** [comment]
@spazznolo Why was this issue closed? How did you resolve this problem? I am facing a similar issue. My file is fairly large - 5 MB when I export from mapshaper. My file before mapshaper is [here](https://drive.google.com/file/d/1yzJVGE7JKJ363-oFnXwf8fHx50ZKntIp/view?usp=sharing) and after exporting from mapshaper [here](https://drive.google.com/file/d/1tkG48Hk6MVAXFewyaFkyFZ5CgPz6enjq/view?usp=sharing)

**Comment by macrigiuseppe** [comment]
when trying the above file, kepler.gl will crash and show the following in the console:
<img width="1792" alt="Screen Shot 2019-04-26 at 2 30 18 PM" src="https://user-images.githubusercontent.com/2554552/56837615-e8343d00-682f-11e9-9e72-6e1ef018ed1d.png">

**Comment by macrigiuseppe** [comment]
@chintanp i checked your files and it looks your files don't contain actual lat/long coordinates ([ 795609.717250004410744, 618963.649000003933907, 0.0 ]); unfortunately Kepler.gl is only able to handle lat/long coordinates
