### ISSUE TITLE
Better image export

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#326]
**Describe the bug**
The current export functionality requires to load css and it's trigger a CORS request and it fails.

**To Reproduce**
1. Create a map
2. Try to export the map

**Expected behavior**
Export image should work properly

Multiple tasks were filed against this issue:
#212 
#155 
#150 

**Possible Implementation**
- Use [html-screen-capture-js](https://www.npmjs.com/package/html-screen-capture-js) to generate image (rulesToAddToDocStyle for ratio)

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/360
