### ISSUE TITLE
Embed an interactive map as html

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#327]
**Is your feature request related to a problem? Please describe.**
Currently there is now way to export an existing map as an html file

**Describe the solution you'd like**
As user I should be able to export the map from the export bar

***Potential designs:***
- Independent options
<img width="668" alt="screen shot 2019-01-13 at 12 59 57 pm" src="https://user-images.githubusercontent.com/2554552/51090927-69ac0780-1738-11e9-98a7-f59c6e4bf483.png">

- or we can combine "Export map url" and "Export map" into a single element.
<img width="637" alt="screen shot 2019-01-13 at 1 42 28 pm" src="https://user-images.githubusercontent.com/2554552/51091021-6a916900-1739-11e9-8ef6-70677f820769.png">

And in the export modal dialog we provide the following options:
- Export map to an html file
- Export to Cloud and generate permalink

Existing issues affected:
#301 
#223 possible reference

***Possible implementation***
- Convert the entire page into a string and save it as html file using [html-screen-capture-js](https://www.npmjs.com/package/html-screen-capture-js). Maybe using webworkers to speed up the process.
- Static template:
  - Publish a build of kepler.gl to cdn
  - Generate a static html file we are going to use as the template, it should be automatically generated during deploy
  - Once users export a map, we can simply hydrate the template with data/configuration map

***Considerations***
- Should we link js and css externally or keep them in line?
- What happens if data is too big? Can we combine everything in one file or should we use an external file?

**Comment by roqueleal** [comment]
We hope soon you can develop the module of imbibing soon! Greetings excellent contributions

**Comment by macrigiuseppe** [comment]
reference: #331

**Comment by macrigiuseppe** [comment]
This is blocked by #332

**Comment by schnerd** [comment]
One consideration that I don't see listed in the issue: **Versioning of builds published to the CDN.**

If the static HTML people are using makes any assumptions about the kepler JS API (or CSS for that matter), then the builds published to the CDN should probably be versioned. Otherwise publishing a new Kepler build with backwards incompatible changes could break all these old static pages. If you make the bundled code a part of the published npm package, you could probably use [unpkg](https://unpkg.com/) as a free CDN for this.

**Comment by macrigiuseppe** [comment]
> One consideration that I don't see listed in the issue: **Versioning of builds published to the CDN.**
> 
> If the static HTML people are using makes any assumptions about the kepler JS API (or CSS for that matter), then the builds published to the CDN should probably be versioned. Otherwise publishing a new Kepler build with backwards incompatible changes could break all these old static pages. If you make the bundled code a part of the published npm package, you could probably use [unpkg](https://unpkg.com/) as a free CDN for this.

@schnerd unpkg is exactly the strategy we have decided to pursuit .

**Comment by briantcl** [comment]
as discussed in the sprint meeting, we will also test it out by introducing this new feature in a medium ariticle as well. thanks!

**Comment by Jesterary** [comment]
How soon will this feature be available? It will be very helpful!

**Comment by macrigiuseppe** [comment]
> How soon will this feature be available? It will be very helpful!

@Jesterary once this is merged in: https://github.com/uber/kepler.gl/pull/366

**Comment by vulkenree** [comment]
can I easily embed kepler.gl to a dash app?
