### ISSUE TITLE
Publish kepler.gl to cdn as UMD package

### ISSUE THREAD

**Issue by heshan0131** [uber/kepler.gl#332]
**Feature**
Add build script to create a umd bundle

**Solution**

1. Create build script to build the umd bundle, unpkg will automatically publish it. 
[UNPGK instruction](https://unpkg.com/)
   - Add the umd (or dist) directory to your .gitignore file
   - Add the umd directory to your files array inpackage.json
   - Use a build script to generate your UMD build in the umd directory when you publish

[Example: deck.gl webpack.config]( https://github.com/uber/deck.gl/blob/master/modules/lite/webpack.config.js#L50-L68)
[Example: deck.gl build.sh](https://github.com/uber/deck.gl/blob/master/modules/main/build.sh)

2. Exclude deck.gl, react, mapbox.gl in the bundle

**Alternative**
Using rollup to build for better tree shaking. However will add to dev dependencids
[Example: Provide umd bundle](https://github.com/uber/react-map-gl/pull/581)

**Comment by macrigiuseppe** [comment]
I also found a different option:
- Babel babel-plugin-transform-es2015-modules-umd

Since we already build the library using babel, we can reuse our current work

**Comment by macrigiuseppe** [comment]
Completed and merged onto master
