### ISSUE TITLE
Error while using it in react-native app.

### ISSUE THREAD

**Issue by naveen-agula** [uber/kepler.gl#345]
Hi, 
I'm getting the 
"error: bundling failed: Error: Unable to resolve module `assert` from `/Users/KeplerTestApp/node_modules/kepler.gl/dist/processors/data-processor.js`: Module `assert` does not exist in the Haste module map"

When I import the "import KeplerGl from 'kepler.gl';" in React-Native App. Please help me on this.
I have attached the screenshot. 

![screen shot 2019-01-25 at 5 38 31 pm](https://user-images.githubusercontent.com/7720676/51745400-b5f82f80-20c8-11e9-8161-5873070f3964.png)

**Comment by cc189** [comment]
have the same problem

**Comment by macrigiuseppe** [comment]
Hi @naveen-agula , thank you for sharing this with us. Unfortunately we never tested kepler.gl with react-native but if you shared your code with us or a demo project where we can replicate your issue we are going to take a look at.

Thank you.

**Comment by macrigiuseppe** [comment]
@naveen-agula it looks some standard Node core modules, e.g. assert, are not included in react-native. Please check this out: https://github.com/facebook/react-native/issues/21405 for more info
