### ISSUE TITLE
Kepler.gl should allow developers to pass a StyledComponents theme to override the original style

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#346]
**Describe the bug**
Currently Kepler.gl implements styling using styled-components and inject its own theme. Unfortunately there is no way for the parent app to inject a different styled-components theme to override/extend the existing one.

**Comment by IgorWilbert** [comment]
Hey @macrigiuseppe ! Are you still working on this? Thanks!

**Comment by macrigiuseppe** [comment]
> Hey @macrigiuseppe ! Are you still working on this? Thanks!

I haven't started yet, but i will get on this soon.

**Comment by macrigiuseppe** [comment]
My solution:
kepler.gl should access a new prop: them which will allow developers to pass a custom theme and in keplergl.js

we perform the following changes:
```javascript
import {theme as basicTheme} from 'styles/base';

render() {
  return (
    <ThemeProvider theme={{...this.props.them, ...theme}}> 
      ...
    </ThemeProvider>
  );
}
```

**Comment by macrigiuseppe** [comment]
@IgorWilbert created a new pull request: https://github.com/uber/kepler.gl/pull/424
