### ISSUE TITLE
Export Image Broken

### ISSUE THREAD

**Issue by sTranaeus** [uber/kepler.gl#353]
**Describe the bug**
Whenever I click Export Image, Kepler freezes and I have to close the window and reopen it. This happens every time I have tried to export an image for the past 1-2 weeks. When I inspect the webpage on Chrome, there is a re-occuring `bundle.js:79 Uncaught TypeError: Cannot read property '3d building' of undefined` error after clicking Export Image.

**To Reproduce**
1. Create anything on Kepler
2. Click Export Image
3. Kepler should freeze and become unresponsive.

**Expected behavior**
Expected the Export Image window to appear as it used to - which would allow me to configure some image settings and then export it.

**Desktop (please complete the following information):**
 - OS: OS X 10.14.2
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by wonderino** [comment]
I also experienced this situation after updating to v0.2.1

**Comment by anapastore** [comment]
Similar issues with Safari and Firefox (Ubuntu and OS)

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/360

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/361

**Comment by macrigiuseppe** [comment]
fixed

**Comment by anapastore** [comment]
Still not properly working. It saves an empty figure.

**Comment by macrigiuseppe** [comment]
> Still not properly working in Safari. It saves an empty figure.

@anapastore can you please open a new issue? thank you
