### ISSUE TITLE
Kepler.gl won't run unless user exports mabox token in the environment

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#355]
**Describe the bug**
When using Kepler.gl in an environment which doesn't export the mapbox token we get the following error

Can't read env of null. The problem is related to the following file and line:
3d-buildings-utils:27
```
const MAPBOX_TOKEN = process.env.MapboxAccessToken;
```
**To Reproduce**
In order to reproduce the issue
1. Change the demo app and pass the mapboxtoken hardcoded to kepler.gl. This will simulate a use case without the process object
2. Run the demo app
3. Open the console and you should see the error

**Expected behavior**
The internal part of the library should not rely on external variable, such as the process object, and instead the mapbox token should be propagated from the kepelr.gl component to the rest of the components.
This is a blocker for single page export, since there is no process object.
We need to define a single point where users provide their own mapbox token.

**Comment by macrigiuseppe** [comment]
Possible alternatives:
- Pass mapboxAccessToken as a paramenter and bind getTileData with mapboxAccessToken when calling renderLayers()
- Create a mapbox client where ew can funnel all mapbox requests into and inject mapboxAccessToken

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/360

**Comment by macrigiuseppe** [comment]
fixed
