### ISSUE TITLE
Couldn't use with React 16.4+ due to styled-components deps on componentWillMount

### ISSUE THREAD

**Issue by VigneshPeriasami** [uber/kepler.gl#364]
**Bug Description**
`styled-components` ThemeProvider v2.2.4 relies on componentWillMount which on react 16.4+ results in broadcast undefined error

`styled-components` issue link related to lifecycle dependencies. https://github.com/styled-components/styled-components/issues/1575

**styled-components ThemeProvider LineOfError**
Using KeplerGL component in React 16.4+ breaks at ThemeProvider broadcast.subscribe
https://github.com/styled-components/styled-components/blob/v2.2.4/src/models/ThemeProvider.js#L66

**To Reproduce**
Use KeplerGL component in react v16.4+

**Expected behavior**
KeplerGL component to render in React v16.4+

**Comment by VigneshPeriasami** [comment]
I can see the fix is already in progress, this will do https://github.com/uber/kepler.gl/pull/363

**Comment by macrigiuseppe** [comment]
> I can see the fix is already in progress, this will do #363

This should be fixed soon

**Comment by macrigiuseppe** [comment]
@VigneshPeriasami have a look at this pull request https://github.com/uber/kepler.gl/pull/423

**Comment by VigneshPeriasami** [comment]
@macrigiuseppe looks good to me, there are few more components under `common` which depends on `innerRef` deprecated prop from `styled-components` while back I have created a forked copy to fix issues that I was running into.

Thanks, really appreciate the efforts.

**innerRef dependent components**
https://github.com/VigneshPeriasami/kepler.gl/commit/9de55a9a9342261a87b13fa28ee46a6af8d09cff
