### ISSUE TITLE
[Style] Allow passing a custom theme object to change the styling

### ISSUE THREAD

**Issue by heshan0131** [uber/kepler.gl#374]
**Is your feature request related to a problem? Please describe.**
There is no easy way to custom kepler.gl UI styling

**Describe the solution you'd like**
kepler.gl uses styled-component, its looking & feel mostly controlled by a single json [theme object][https://github.com/uber/kepler.gl/blob/master/src/styles/base.js]. 

We will use dependency injection, add `themeFactory` as another dependency of `KeplerGl` component, and make the theme object as the return of `themeFactory`.  User can import default theme object, merge it with their customTheme, and inject a customThemeFactory.

**Comment by macrigiuseppe** [comment]
is this related to this one? https://github.com/uber/kepler.gl/issues/346

**Comment by macrigiuseppe** [comment]
Implemented in this one: https://github.com/uber/kepler.gl/pull/424
