### ISSUE TITLE
Publish public roadmap

### ISSUE THREAD

**Issue by heshan0131** [uber/kepler.gl#387]

**Comment by heshan0131** [comment]
Roadmap published to 
https://github.com/uber/kepler.gl/wiki/Kepler.gl-2019-Roadmap

**Comment by sn3fru** [comment]
Could we have the roadmap updated?
I know this is an unimportant demand compared to the development of new features, but having an upgraded roadmap will help hundreds (or thousands) of people program when the features we need will come in the future.
@heshan0131

**Comment by frhino** [comment]
@heshan0131 May I ask what tool you used to create your gantt-style roadmap in the wiki? It looks great!

**Comment by heshan0131** [comment]
Road map is updated. and @frhino I used Lucidchart :)
