### ISSUE TITLE
react-anything-sortable is no longer maintained. Need a replacement

### ISSUE THREAD

**Issue by macrigiuseppe** [uber/kepler.gl#422]
react-anything-sortable is no longer maintained and last commit was performed on march 2018.

We need a good replacement and must support react 16

**Comment by macrigiuseppe** [comment]
Possible candidate
http://react-dnd.github.io/react-dnd/examples/sortable/simple

**Comment by benshope** [comment]
I just started checking out `react-sortable-hoc` because it's based on `react-virtualized`, has good examples, and has a small bundle size.  Not 100% sure it's good but it might be worth a look

**Comment by briantcl** [comment]
completed in spring Mar 22, 2019
