### ISSUE TITLE
Function not found

### ISSUE THREAD

**Issue by jofri99** [uber/kepler.gl#440]
**Describe the bug**
When I try to run your example replace-component I get the following error:
TypeError: _components.PanelToggleFactory is not a function

**To Reproduce**
1. clone git https://github.com/uber/kepler.gl.git
2. got to kepler.gl/examples/replace-component/src
3. run sudo npm install
4. run export MapboxAccessToken=MapboxToken
5. run npm start
6. The error appears in the Browser console

**Expected behavior**
How to fix the issue when its mine

**Screenshots**
![grafik](https://user-images.githubusercontent.com/31164173/54291721-491ff280-45ad-11e9-8fc6-8776fa21fe6a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Firefox 65.0.1 (64-Bit)

**Smartphone (please complete the following information):**
No Smartphone

**Additional context**
I get this problem while I try to understand how to customize the UI of keplergl

**Comment by hb0** [comment]
This error does not occur (using the reproduction steps above) with the version on tag 0.2.3 (commit https://github.com/uber/kepler.gl/commit/9e750a069a954102c49c5c532f4001490d2ede4a).

**Comment by heshan0131** [comment]
This should be fixed in 0.2.4, at the meantime comment out line 61 in `examples/replace-component/src/app.js` will get the app up and running

**Comment by hb0** [comment]
Thanks, this fixes it!

```
const KeplerGl = injectComponents([
  [SidebarFactory, CustomSidebarFactory],
  [PanelHeaderFactory, CustomPanelHeaderFactory]
//,
//  [PanelToggleFactory, CustomPanelToggleFactory]
]);
```

**Comment by heshan0131** [comment]
0.2.4 is published, and examples are updated. resolve it now
