### ISSUE TITLE
Points disappear when panning

### ISSUE THREAD

**Issue by chrisirhc** [uber/kepler.gl#443]
**Describe the bug**
When panning on the map, points can disappear when panning pass a certain line.

**To Reproduce**
Steps to reproduce the behavior (alternatively access [this url](http://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/5le4srmqj863b69/keplergl_razvxzw.json)):
1. Go to https://kepler.gl/demo
2. Upload the dataset from https://dl.dropboxusercontent.com/s/5le4srmqj863b69/keplergl_razvxzw.json . Original source: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv (This data will change from day to day, but I've saved this data at)
3. Pan left and right as "North Pacific Ocean" is around the middle of the screen.
4. See points disappearing and reappearing

**Expected behavior**
Points should stay visible throughout panning.

**Screenshots**
![kepler-bug](https://user-images.githubusercontent.com/132584/54467679-f9bffa80-4743-11e9-834e-7b9d6bbb245d.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version tested on Canary and current stable version

**Additional context**

**Comment by heshan0131** [comment]
Tracked in deck.gl https://github.com/uber/deck.gl/pull/2147
solution is to add `wrapLongitude: true`

**Comment by macrigiuseppe** [comment]
Fixed and merged
