### ISSUE TITLE
csv loading but not displayed

### ISSUE THREAD

**Issue by djouallah** [uber/kepler.gl#444]
I am trying to load 58K points, the csv file load but nothing is displayed, here is an example of my coordinates

id | x_lon | y_lat | z_coordinate
A-27-01 | 143.4907 | -34.7557 | 61.4342
A-27-02 | 143.4907 | -34.7556 | 61.4498
A-27-03 | 143.4907 | -34.7556 | 61.4649
A-27-04 | 143.4907 | -34.7555 | 61.4795
A-27-05 | 143.4907 | -34.7554 | 61.4922
A-27-06 | 143.4907 | -34.7554 | 61.5431
A-27-07 | 143.4907 | -34.7553 | 61.6151
A-27-08 | 143.4907 | -34.7552 | 61.6892
A-27-09 | 143.4907 | -34.7551 | 61.758
A-27-10 | 143.4907 | -34.7551 | 61.837
A-27-11 | 143.4907 | -34.755 | 61.919
A-27-12 | 143.4907 | -34.7549 | 61.9981

what I am doing wrong

**Comment by djouallah** [comment]
When i save the same data as a wkt or geojson,  it works perfectly?

**Comment by chrisirhc** [comment]
Hi @djouallah , that is not a CSV, a CSV is comma-separated like: 
```
id,x_lon,y_lat,z_coordinate
A-27-01,143.4907,-34.7557,61.4342
```
