### ISSUE TITLE
Swapping out backing map

### ISSUE THREAD

**Issue by jkblgithub** [uber/kepler.gl#449]
We have designed a custom map using Mapbox studio. We have a link to this map in the format of https://api.mapbox.com/styles/v1/<our company name>/?????.html?fresh=true&title=true&access_token=<our access token>

We would like to use this as the backing map in kepler, but I cant see a way to do this - is it possible please?

**Comment by erickndava** [comment]
I believe the Kepler.gl team has this planned as in #164 or #406

**Comment by jkblgithub** [comment]
Thank you

> I believe the Kepler.gl team has this planned as in #164 or #406

**Comment by chrisirhc** [comment]
Are you referring to custom map styles: https://github.com/uber/kepler.gl/blob/34dd31de87fd1b2be68c6d426a93e76d6cd065be/docs/user-guides/f-map-styles/3-custom-styles.md ?

**Comment by jkblgithub** [comment]
Yes! Sorry I missed that - Thank you
