### ISSUE TITLE
Export Map window is not showing properly

### ISSUE THREAD

**Issue by briantcl** [uber/kepler.gl#454]
**Describe the bug**

After clicking 'Export Map', the window is populating content from 'Export Configuration' but not 'Export Map'.

![image](https://user-images.githubusercontent.com/13949281/55041511-960eba80-4fea-11e9-872f-1ab731fce19f.png)

thanks for looking into it!

**Comment by macrigiuseppe** [comment]
fixed in this one: https://github.com/uber/kepler.gl/pull/455
