### ISSUE TITLE
open-modal example TypeError

### ISSUE THREAD

**Issue by julianheinrich** [uber/kepler.gl#470]
**Describe the bug**
the open-modal demo throws the following error in the developer console of Firefox 60.4.0:
`TypeError: SelectText.extend is not a function` in `styled-components.js:273` and shows a blank page.

**To Reproduce**
1. `cd examples/open-modal`
2. `export MapboxAccessToken=myTokenHere`
3. `yarn --ignore-engines`
4.`yarn start` or `npm start`

**Expected behavior**
anything else than a blank page.

**Screenshots**
![image](https://user-images.githubusercontent.com/7494632/56221397-7eb37200-606a-11e9-9917-7d2ab62aae53.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox 
 - Version 60.4.

**Comment by heshan0131** [comment]
Upgrade to kepler.gl@1.0.0-0 will solve it. I will also update the repo on our side
