### ISSUE TITLE
Unable to upload data on local

### ISSUE THREAD

**Issue by snehabhapkar** [uber/kepler.gl#474]
I'm unable to upload the geojson, json or csv file on local repository. The same file worked fine on [Kepler demo](https://kepler.gl/demo).
However on local env when I upload the file, it keeps on spinning for longer time and nothing gets uploaded

**Screenshot**
<img width="1517" alt="Screen Shot 2019-04-17 at 4 57 48 pm" src="https://user-images.githubusercontent.com/2749122/56267379-fe584400-6131-11e9-8ed8-fc078c32205b.png">

**Additional context**
React 16.8
Redux 4.0.1
react-redux 6.0.1

**Comment by snehabhapkar** [comment]
After updating the kepler version to v1.0.0-0 the warning message is gone. But still not able to upload the data on local. It keeps on spinning for long time.

Am I missing anything? My component file looks like below

![Screen Shot 2019-04-18 at 12 19 14 pm](https://user-images.githubusercontent.com/2749122/56332591-3912b880-61d4-11e9-9356-1e135a0a0d1e.png)

**Comment by snehabhapkar** [comment]
After updating the kepler version to v1.0.0-0 the warning message is gone. But still not able to upload the data on local. It keeps on spinning for long time.

Am I missing anything? My component file looks like below

![Screen Shot 2019-04-18 at 12 23 06 pm](https://user-images.githubusercontent.com/2749122/56332719-ce15b180-61d4-11e9-8b96-8a610d7cda2a.png)

**Comment by macrigiuseppe** [comment]
@snehabhapkar can you please share the file you are using or a sample in order to troubleshoot your issue?
thank you

**Comment by snehabhapkar** [comment]
Hi @macrigiuseppe, please find file below

import React, {Component} from 'react';
import { ReactReduxContext } from 'react-redux'
import {connect} from 'react-redux';
import { withRouter } from "react-router";
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer';
import KeplerGl from 'kepler.gl';

const MAPBOX_TOKEN = process.env.MapboxAccessToken; 
const emptyTheme = {};
class App extends Component {

  render() {
    return (
      <ReactReduxContext.Consumer>
        {({ store }) => (
          <div style={{position: 'absolute', width: '100%', height: '100%'}}>
          <AutoSizer>
            {({height, width}) => (
              <KeplerGl
                mapboxApiAccessToken={MAPBOX_TOKEN}
                id="map"
                width={width}
                height={height}
                store={store}
                theme={emptyTheme}
              />
            )}
          </AutoSizer>
        </div>
        )}
      </ReactReduxContext.Consumer>

    );
  }
}

const mapStateToProps = state => state;
const dispatchToProps = dispatch => ({dispatch});

export default withRouter(connect(mapStateToProps, dispatchToProps)(App));


**Additional context:**
My package.json dependecies

"dependencies": {
    "@google/markerclustererplus": "^2.1.11",
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
    "connected-react-router": "6.3.2",
    "es6-shim": "^0.35.5",
    "google-maps-react": "^2.0.2",
    "kepler.gl": "^1.0.0-0",
    "node-sass": "^4.11.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^6.0.1",
    "react-render-html": "0.6.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "react-spinners": "0.5.4",
    "react-test-renderer": "^16.8.6",
    "react-virtualized": "^9.18.5",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.1.0",
    "redux-promise-middleware": "^6.1.0",
    "redux-saga": "^1.0.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.1.3"
  }

**Comment by macrigiuseppe** [comment]
> Hi @macrigiuseppe, I have uploaded the file with .txt extension. Kindly rename file back to .js for investigation
> 
> [Maps.txt](https://github.com/uber/kepler.gl/files/3106240/Maps.txt)
> 
> Additional Context:
> My package.json dependencies are as below
> "dependencies": {
> "@google/markerclustererplus": "^2.1.11",
> "@material-ui/core": "^3.9.3",
> "@material-ui/icons": "^3.0.2",
> "connected-react-router": "6.3.2",
> "es6-shim": "^0.35.5",
> "google-maps-react": "^2.0.2",
> "kepler.gl": "^1.0.0-0",
> "node-sass": "^4.11.0",
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "react-redux": "^6.0.1",
> "react-render-html": "0.6.0",
> "react-router-dom": "^5.0.0",
> "react-scripts": "2.1.8",
> "react-spinners": "0.5.4",
> "react-test-renderer": "^16.8.6",
> "react-virtualized": "^9.18.5",
> "redux": "^4.0.1",
> "redux-devtools-extension": "^2.13.8",
> "redux-form": "^8.1.0",
> "redux-promise-middleware": "^6.1.0",
> "redux-saga": "^1.0.1",
> "redux-thunk": "^2.3.0",
> "styled-components": "^4.1.3"
> },

@snehabhapkar I need the data file you are trying to upload to create your map, can you provide the json, csv file you are trying to use?

**Comment by snehabhapkar** [comment]
@macrigiuseppe I am using kepler gl sample csv file. Attached the same
[kepler-gl_dataset.csv.zip](https://github.com/uber/kepler.gl/files/3110054/kepler-gl_dataset.csv.zip)

Also I have uploaded my sample project on github incase you want to reproduce the issue using sample data file
https://github.com/snehabhapkar/kepler-demo

**Comment by macrigiuseppe** [comment]
hey @snehabhapkar,
you are missing a middleware component in your app __react-palm__. Without such component file uploading will not work

Please check this link for references: https://github.com/uber/kepler.gl/blob/master/examples/demo-app/src/store.js#L37

**Comment by snehabhapkar** [comment]
hey @macrigiuseppe,
Thanks for the solution! My bad I missed it. 
Now it is working as expected hence closing the issue.
