### ISSUE TITLE
Custom Theme don't work

### ISSUE THREAD

**Issue by darkat** [uber/kepler.gl#476]
**Is your feature request related to a problem? Please describe.**
Custom theme don't work with ThemeProvider or Props in local.
My code:

```
import KeplerGl from 'kepler.gl';

class Kepler extends React.Component {
  render() {
    const mapboxApiAccessToken = '';
    const customTheme = {
      sidePanelBg: '#ff0000',
      titleTextColor: '#ff0000',
      sidePanelHeaderBg: '#ff0000',
      subtextColorActive: '#ff0000',
    };
   return <KeplerGl mapboxApiAccessToken={mapboxApiAccessToken} theme={customTheme} store={store} />
}
```

**Additional context**
React 16.6.3
Redux 4.0.1
react-redux 6.0.0

**Comment by heshan0131** [comment]
You need `kepler.gl@1.0.0-0` to use the theme prop. `1.0.0-0` is using react 0.16, so you will need to upgrade react as well

**Comment by heshan0131** [comment]
Master has been updated, pull latest master, in `custom-theme` folder run  `rm -r node_modules && rm yarn.lock && yarn --ignore-engines && npm start` should work

**Comment by macrigiuseppe** [comment]
not a bug
