### ISSUE TITLE
DateTime fields read as strings

### ISSUE THREAD

**Issue by mistyblue17** [uber/kepler.gl#78]
Kepler.gl looks super cool and I'm excited to be able to use it. After adding my data, my fields only show up as integers and strings, even my DateTime field. I've tried going back into LibreCalc to set the format to date, time, and custom YYYY/MM/DD HH:MM:SS format, but it still just comes through as a string after upload the UTF-8 CSV file.
[SyracuseSiteData_Qonly_UTF-8.zip](https://github.com/uber/kepler.gl/files/2059131/SyracuseSiteData_Qonly_UTF-8.zip)

**Comment by heshan0131** [comment]
@mistyblue17 our current date time checks doesn't cover `YYYY/MM` case yet and is always expect a time, However `YYYY/MM/DD HH:MM` should work. I added a column `datetime_1` in your csv in `YYYY/MM/DD HH:MM` format and was able to create a time filter

![screen shot 2018-05-31 at 12 25 22 pm](https://user-images.githubusercontent.com/3605556/40803551-c84f3cee-64cd-11e8-9a97-3d0c208b6d0c.png)
![screen shot 2018-05-31 at 12 26 20 pm](https://user-images.githubusercontent.com/3605556/40803603-e12a9dee-64cd-11e8-9729-4179f513bfb0.png)

[SyracuseSiteData_Qonly_UTF-8_fix.zip](https://github.com/uber/kepler.gl/files/2059748/SyracuseSiteData_Qonly_UTF-8_fix.zip)

**Comment by Philwang3** [comment]
Hi, I am planning to use it on a history visualization demo. May I ask how kepler.gl handle date time before christ(B.C. time)? Is it "-700-03-01" or "700-03-01 B.C./bc" or "0700-03-01 B.C./bc"?

**Comment by FDenker** [comment]
@Philwang3  were you able to solve this problem because I am having similar issues

**Comment by gudeso23** [comment]
Thanks, @heshan0131 heshan0131

I have the same issue with the date formats, how did u make the conversion? I was trying to do using ArcGIS Pro Date Convertor, but that did not resolve the issue. Ori
