### ISSUE TITLE
GeometryCollection GeoJSON not supported

### ISSUE THREAD

**Issue by Allsimon** [uber/kepler.gl#80]
Adding a GeometryCollection GeoJson layer throw this error:

```
deck.gl deck.gl error during initialization of <GeoJsonLayer:'vyik0jh'> Error: GeoJsonLayer: GeometryCollection not supported. 
Error: GeoJsonLayer: GeometryCollection not supported.
```

You can reproduce it with [testCase.csv.zip](https://github.com/uber/kepler.gl/files/2062092/testCase.csv.zip)

**Comment by yiyaya66** [comment]
Duplicate ticket to: https://github.com/uber/kepler.gl/issues/103
