### ISSUE TITLE
P1: Lines are wildly sticking out and will not scale up or down by zooming

### ISSUE THREAD

**Issue by yiyaya66** [uber/kepler.gl#83]
started seeing this issue when I drop a geojson into Kepler. tried a couple of files so far. they show like expected in QGIS and other tools 

when I zoom in, it doesn't go away but setting the stroke width to 0.3 or something super small hides of an issue

![image pasted at 2018-5-11 13-41](https://user-images.githubusercontent.com/28815578/40854210-86c4b354-6585-11e8-89cb-0a59d3825d64.png)

**Comment by yiyaya66** [comment]
![screen shot 2018-05-17 at 8 42 39 am](https://user-images.githubusercontent.com/28815578/40854685-0b77fdda-6587-11e8-8d58-424a9fd3291a.png)

**Comment by heshan0131** [comment]
same as https://github.com/uber/kepler.gl/issues/86
