### ISSUE TITLE
what is the best way to go about making a sharable version of the map?

### ISSUE THREAD

**Issue by JustinGOSSES** [uber/kepler.gl#94]
I've really enjoyed working with data in keplergl and have recommended it to others. One feedback question I've gotten back, and I've had difficulty with as well, is :

**what is the best way to go about making a sharable version of the map?** 

It is very easy and intuitive to make things from client-side GUI, but they go away when you close the browser. There is export functionality, but not a lot of documentation on how to go about building a map with that exported data and configuration that you could share via github pages. There have been some great Medium posts on how users can load their own data into the application, perhaps something similar would be helpful if not here within a separate readme? 

If someone wants to take this on, feel free to tag me for feedback / edits.

**Comment by chrisirhc** [comment]
There's a tutorial that we've put up on http://vis.academy/#/kepler.gl that demonstrates how you can extract the state to save it. You can persist the configuration and data to any backend as needed and load it back.

**Comment by heshan0131** [comment]
@JustinGOSSES right now, without building an app, you can export the data AND config from kepler.gl UI as single JSON, later uploaded by simply drag and drop the exported json into the add data modal dialog. This way you can at least reload the map you previously created. 

Nevertheless, I think adding a tutorial to show how to create a kepler.gl map in code pen, blo.ck or Observrable sounds like a really good idea. I think @akre54 is working on a kepler.gl observrable demo?

**Comment by JustinGOSSES** [comment]
Thanks for the responses! They answer my immediate questions that led to starting this issue. I added a slight change in wording to improve clarity on the file upload window  #115

Additional demos linked to the main readme or documentation would be great in helping make persistent maps with this tool.
