### ISSUE TITLE
Geojson files can't be uploaded

### ISSUE THREAD

**Issue by daniel-lij** [uber/kepler.gl#96]
Hello, I want to see the upload file data structure, so according to the method provided by https://medium.com/vis-gl/visualizing-u-s-county-unemployment-with-kepler-gl-c5f2ed31c71 I generated a counties-unemployment.geojson file, the file is only about 1800K, but can not be uploaded to the kepler.gl, I do not know what to do Is it? If you need the file I generated, I can send it to you. Thank you.

**Comment by daniel-lij** [comment]
My file was passed through http://mapshaper.org/, and I've put all my files on the GitHub, address: https://github.com/daniel-lij/keplerTest, I hope the teacher can take the time to see it. Thank you

**Comment by heshan0131** [comment]
@daniel-lij The `counties.json` loaded fine. the `counties-unemployment.geojson` is not a valid json. Please take a look at end of the file, it ends at `"ALAND": 3703639185, "AWATER": 44411469, "labor_force"` without closing. it is incomplete

**Comment by yiyaya66** [comment]
@daniel-lij closing this issue for now. Please check Shan's comments and feel free to reopen if issue remains.

**Comment by alexlorenzo** [comment]
Hello,

Having the same issue but using geojson file from France, Germany or UK. Impossible to load any geojson file in Kepler. Any ideas? 
Thanks
